name: jot
acronym: JOT
language: en
forge: github
members:
  ai:claude@joy:
    capabilities:
      conceive: {}
      plan: {}
      design: {}
      implement: {}
      test: {}
      review: {}
      document: {}
      create: {}
      assign: {}
  horst.schwarz@joydev.com:
    capabilities: all
    public_key: 4671edfbfff3d404b47211988f9381d2f75a66e0eea11252fe224e5209b44930
    salt: 652a4bce18eac64065ff69636a54ce4d0adad7c1efac82c2c6ea8cf7dc4d3408
    ai_tokens:
      ai:claude@joy:
        token_key: 5970baada727234c400ab334869aabe0737154f5bab3595e1bf87fb45b5f8c76
        created: 2026-04-08T17:12:08.984473709Z
created: 2026-03-20T10:51:52.574885092Z
release:
  version-files:
  - path: crates/jot-core/Cargo.toml
    key: package.version
  - path: crates/jot-cli/Cargo.toml
    key: package.version
