name: jyn
acronym: JYN
language: en
forge: github
members:
  ai:claude@joy:
    capabilities:
      conceive: {}
      plan: {}
      design: {}
      implement: {}
      test: {}
      review: {}
      document: {}
      create: {}
      assign: {}
    attestation:
      attester: horst.schwarz@joydev.com
      signed_fields:
        email: ai:claude@joy
        capabilities:
          conceive: {}
          plan: {}
          design: {}
          implement: {}
          test: {}
          review: {}
          document: {}
          create: {}
          assign: {}
      signed_at: 2026-04-20T19:04:20.194901689Z
      signature: d5edf75d8ec7d2f5422f478e081d68ecb7685f5a18a7a76fb5a4972a454e51c3f8f928d6d4bd778df8b2816bb423b157eaa6a2497959bff0a3dec8be4938d601
  horst.schwarz@joydev.com:
    capabilities: all
    verify_key: 4671edfbfff3d404b47211988f9381d2f75a66e0eea11252fe224e5209b44930
    kdf_nonce: 652a4bce18eac64065ff69636a54ce4d0adad7c1efac82c2c6ea8cf7dc4d3408
    seed_wrap_passphrase: 0cd49bff630d5607e60e09844a2aa644c8835719ba5a5f40cf74f2f50e64b3152942640bd22b1cfb020cb6823f9b99a1f9d8cf7bdeae78e5efcf4a44
    seed_wrap_recovery: 234f5f9824de2393695f3a24ca1ee26cc545681cd1add7ffef84c4a02088b43886588ae8ea83cfd209ffe4064f4bebbeb4c8a5396b7d5eb7576fa0cd
    ai_delegations:
      ai:claude@joy:
        delegation_verifier: d935686271cfe16dbe0a4e14f14d4e3bef31cc033dea80b2d9f6544c4a79c757
        created: 2026-04-18T10:22:40.963904117Z
created: 2026-03-20T10:51:52.574885092Z
release:
  version-files:
  - crates/jyn-core/Cargo.toml
  - crates/jyn-cli/Cargo.toml
  - crates/jyn/Cargo.toml
